name: ecourse_flutter_v2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  easy_localization: ^3.0.5
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.8
  dots_indicator: ^4.0.1
  flutter_svg: ^2.0.17
  connectivity_plus: ^6.1.3
  dio_cache_interceptor: ^3.5.1
  flutter_otp_text_field: ^1.4.0+2
  data_table_2: ^2.5.18
  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  animated_read_more_text: ^0.0.6
  flutter_emoji_picker: ^1.0.1
  emoji_picker_flutter: ^4.3.0
  local_auth: ^2.3.0
  flutter_dotenv: ^5.2.1
  cached_network_image: ^3.4.1
  pin_code_fields: ^8.0.1
  url_launcher: ^6.3.1
  chewie: ^1.11.0
  video_player: ^2.9.3
  stylish_dialog: ^1.0.2
  smooth_sheets: ^0.10.2
  lottie: ^3.3.1
  pull_to_refresh_flutter3: ^2.0.2
  socket_io_client: ^3.1.1
  device_info_plus: ^9.1.2
  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^19.0.0
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: GeneralSans
      fonts:
        - asset: assets/fonts/GeneralSans-Regular.otf
          weight: 400
        - asset: assets/fonts/GeneralSans-Medium.otf
          weight: 500
        - asset: assets/fonts/GeneralSans-SemiBold.otf
          weight: 600
        - asset: assets/fonts/GeneralSans-Bold.otf
          weight: 700

  assets:
    - assets/images/
    - assets/svgs/
    - assets/translations/
    - assets/images/onboarding/
    - assets/images/home/
    - .env