// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-oQgvR_WZFxEHQHdbhrXwe1H-zMJ8vpE',
    appId: '1:293150473774:web:f6695daa2874f9c83ce9bf',
    messagingSenderId: '293150473774',
    projectId: 'ecourse-86eb6',
    authDomain: 'ecourse-86eb6.firebaseapp.com',
    storageBucket: 'ecourse-86eb6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo9fXtAL5RnRzRw-fWoNZq2D-XDlm-6zI',
    appId: '1:293150473774:android:27f0f2f9faeca5cb3ce9bf',
    messagingSenderId: '293150473774',
    projectId: 'ecourse-86eb6',
    storageBucket: 'ecourse-86eb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT61A1otp8H7MQmqzhrbv4C3aF8MG7GTc',
    appId: '1:293150473774:ios:386e38cbb333572e3ce9bf',
    messagingSenderId: '293150473774',
    projectId: 'ecourse-86eb6',
    storageBucket: 'ecourse-86eb6.firebasestorage.app',
    iosBundleId: 'com.example.ecourseFlutterV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT61A1otp8H7MQmqzhrbv4C3aF8MG7GTc',
    appId: '1:293150473774:ios:386e38cbb333572e3ce9bf',
    messagingSenderId: '293150473774',
    projectId: 'ecourse-86eb6',
    storageBucket: 'ecourse-86eb6.firebasestorage.app',
    iosBundleId: 'com.example.ecourseFlutterV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-oQgvR_WZFxEHQHdbhrXwe1H-zMJ8vpE',
    appId: '1:293150473774:web:c1c83566884223183ce9bf',
    messagingSenderId: '293150473774',
    projectId: 'ecourse-86eb6',
    authDomain: 'ecourse-86eb6.firebaseapp.com',
    storageBucket: 'ecourse-86eb6.firebasestorage.app',
  );
}
